# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17 for GitHub
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github

    - name: Build with Maven
      run: mvn install -s $GITHUB_WORKSPACE/.m2/settings.xml
      env:
        CS_NEXUS_USER: ${{secrets.CS_NEXUS_USER}}
        CS_NEXUS_PASSWORD: ${{secrets.CS_NEXUS_PASSWORD }}
    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up JDK 17 for CS Nexus
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: cs-nexus-release
        
    - name: Publish to CS Nexus
      run: mvn deploy -Pcs-nexus -s $GITHUB_WORKSPACE/.m2/settings.xml
      env:
        CS_NEXUS_USER: ${{secrets.CS_NEXUS_USER}}
        CS_NEXUS_PASSWORD: ${{secrets.CS_NEXUS_PASSWORD }}